### ISSUE TITLE
Change folder of specs

### ISSUE THREAD

**Issue by vitorgamer58** [herbsjs/herbarium#6]
herbs-cli uses herbarium to separate all tests (specs) and then pass the tests to Aloe, in the current configuration, the specs must be in the same domain folder, next to the usecases:
https://github.com/herbsjs/herbarium/blob/0c6fa7c36bf82ce10423adc832f9e823258fb28d/src/requireAll.js#L31

However, I believe that the most appropriate place for tests is in the tests folder, where it is easier to organize mocks and other auxiliary files for tests, not polluting the domain folder.

Here's an example:

`files = requireAllIfExist({ dirname: __dir + (options.specPath || '/test'), filter: onlySpecs }) `
![Screenshot_7351](https://user-images.githubusercontent.com/8906065/201239456-77e9e2a0-da1b-4afb-ad51-fd0956f5ec6d.png)

### Breaking change

To avoid creating a breaking change, we can create two lists of specs, searching in domain and test, and then merging the lists to return.

**Comment by dalssoft** [comment]
Since the return of `requireAll` is ignored, you could check for more folders.

![image](https://user-images.githubusercontent.com/209287/201442074-f872a944-c02c-4783-b79e-679c6c7269cc.png)

The default is already given (`/src/domain/`), we should have a way to override it or include others folders.

**Comment by vitorgamer58** [comment]
Maybe something like this will work with both folders.
```
files = requireAllIfExist({ dirname: __dir + (options.specPath || '/src/domain/'), filter: onlySpecs })
filesReqAll.specs = files
files = requireAllIfExist({ dirname: __dir + (options.specPath || '/test/'), filter: onlySpecs })
filesReqAll.specs = [...filesReqAll.specs, ...files]
```

**Comment by dalssoft** [comment]
I prefer a way to override instead of trying to add all possible folders

**Comment by vitorgamer58** [comment]
Closed for reasons of: High complexity and low need.
